# version: '3.9'

# services:
#   todo-go-app:
#     build: ./
#     command: ./todo-go-app
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#     environment:
#       - DB_PASSWORD=postgres
#   db:
#     restart: always
#     image: postgres:latest
#     volumes:
#       - ./.database/postgres/data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - 5433:5432

services:
  todo-go-app:
    build: ./ #создание каждый раз нового образа на основе dockerFile
    command: ./todo-go-app
    # image: ponomare0v/todo-go-app:latest #образ с dockerhub
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=postgres

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./schema:/schema
    command: [
      "-path", "/schema",
      "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
      "up"
    ]

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s